### ISSUE TITLE
Custom subdomain for Github Pages

### ISSUE THREAD

**Issue by muratogat** [aktionariat/dashboard-test#1]
As far as I can find, Github Pages doesn't work with subdirectories. (example: www.aktionariat.com/dashboard)
https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

I would go with https://dashboard.aktionariat.com , where Github manages the https anyway.

To do that, we need a CNAME record in our server DNS settings. 

Type: CNAME
From: dashboard.aktionariat.com
To: aktionariat.github.io (and not /dashboard or anything, must point to root)

**Comment by kronrod** [comment]
Done. Hope it works.
